---
# tasks file for Kubernetes Container Runtime Interface (CRI)

- name: Install CRI - containerd.io
  package:
    state: present
    name:
      - containerd.io-1.4.11
  register: cri_installed

- name: Lock containerd version
  command:
    cmd: yum versionlock containerd.io
    warn: false
  when: cri_installed.changed == True

# containerd config default > /etc/containerd/config.toml
- name: Copy CRI configuration - containerd.io
  copy:
    src: "{{ role_path }}/files/cri/containerd-config.toml"
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: "644"
  register: cri_configured

- name: Enable containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes

- name: Restart containerd service after configuration update
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  when: cri_configured.changed == True
