---
# tasks file for Kubernetes Container Network Interface (CNI)

- name: Check if CNI plugin( flannel ) is installed
  stat:
    path: "/etc/cni/net.d/10-flannel.conflist"
  register: cni_installed
  when:
    - inventory_hostname == "m-1-k8s"

- name: debug - cni_installed
  debug:
    msg: "{{ cni_installed }}"
  when:
    - inventory_hostname == "m-1-k8s"

- name: Install CNI plugin( flannel )
  command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    warn: false
  when: inventory_hostname == "m-1-k8s" and ( cni_installed.changed == True or cni_installed.stat.exists == False )
